name: bench

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false

      - name: Get Go environment
        id: go-env
        run: echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.go-env.outputs.modcache }}
          key: benchmark-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            benchmark-${{ runner.os }}-go-

      # Run all benchmarks.
      - name: Run benchmarks
        run: go test -benchtime 100ms -v -bench . -run ^$ ./... | tee benchmark.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-result
          path: benchmark.txt
          if-no-files-found: error
          retention-days: 1
