name: update schema

on:
  workflow_call:
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true
    inputs:
      schema-name:
        type: string
        required: true
      make-command:
        type: string
        required: true
      branch:
        type: string
        default: "feat/update-schema"
        required: false

jobs:
  update-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: update-schema-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            update-schema-${{ runner.os }}-go-

      - name: Update schema
        run: make ${{ inputs.make-command }}

      - name: Generate files
        run: make generate

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'feat(schema): update ${{ inputs.schema-name }} to the latest layer'
          branch: ${{ inputs.branch }}
          delete-branch: true
          token: ${{ steps.generate-token.outputs.token }}
          title: Update ${{ inputs.schema-name }} schema to the latest layer
          body: |
            Update ${{ inputs.schema-name }} schema to the latest layer.
          labels: |
            dependencies
